import { companionService,type CompanionSort } from '../../services/companion'
import { favoriteService } from '../../services/favorite'
import { hospitalService } from '../../services/hospital'
import { serviceService } from '../../services/service'
import { bookingStore,formatMoney } from '../../stores/booking'
import { navigation } from '../../utils/navigation'

const PAGE_SIZE=2
Page({
  data:{query:'',services:[{id:'all',name:'全部'},...serviceService.list().map(i=>({id:i.id,name:i.name})),{id:'tag-children',name:'儿科陪诊'},{id:'tag-elder',name:'老年陪护'}],hospitals:[{id:'all',name:'全部医院'},...hospitalService.list().map(i=>({id:i.id,name:i.shortName}))],genders:[{id:'all',name:'不限'},{id:'female',name:'女性'},{id:'male',name:'男性'}],sorts:[{id:'recommended',name:'综合推荐'},{id:'rating',name:'评分最高'},{id:'count',name:'服务次数'},{id:'price',name:'价格从低到高'}],serviceIndex:0,hospitalIndex:0,genderIndex:0,sortIndex:0,allItems:[] as Array<Record<string,unknown>>,items:[] as Array<Record<string,unknown>>,visibleCount:PAGE_SIZE,hasMore:false,loading:true,error:false,loginVisible:false,pendingFavorite:''},
  onLoad(){this.load()},onShow(){if(!this.data.loading)this.load(false)},onPullDownRefresh(){this.load();wx.stopPullDownRefresh()},onReachBottom(){this.loadMore()},
  load(reset=true){try{const option=this.data.services[this.data.serviceIndex];const hospitalId=this.data.hospitals[this.data.hospitalIndex].id;const gender=this.data.genders[this.data.genderIndex].id;const sort=this.data.sorts[this.data.sortIndex].id as CompanionSort;const serviceId=option.id.startsWith('tag-')?'all':option.id;const tag=option.id==='tag-children'?'儿科':option.id==='tag-elder'?'老年':undefined;const allItems=companionService.list({query:this.data.query,serviceId,tag,hospitalId,gender,sort}).map(i=>({...i,priceText:formatMoney(i.price),hospitalText:i.serviceHospitalIds.map(id=>hospitalService.getById(id)?.shortName).filter(Boolean).slice(0,2).join('、'),favorited:favoriteService.isFavorite('companion',i.id)}));const visibleCount=reset?PAGE_SIZE:Math.max(this.data.visibleCount,PAGE_SIZE);this.setData({allItems,items:allItems.slice(0,visibleCount),visibleCount,hasMore:visibleCount<allItems.length,loading:false,error:false})}catch{this.setData({loading:false,error:true})}},
  loadMore(){if(!this.data.hasMore)return;const visibleCount=this.data.visibleCount+PAGE_SIZE;this.setData({visibleCount,items:this.data.allItems.slice(0,visibleCount),hasMore:visibleCount<this.data.allItems.length})},
  search(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({query:e.detail.value});this.load()},clear(){this.setData({query:''});this.load()},service(e:WechatMiniprogram.PickerChange){this.setData({serviceIndex:Number(e.detail.value)});this.load()},hospital(e:WechatMiniprogram.PickerChange){this.setData({hospitalIndex:Number(e.detail.value)});this.load()},gender(e:WechatMiniprogram.PickerChange){this.setData({genderIndex:Number(e.detail.value)});this.load()},sort(e:WechatMiniprogram.PickerChange){this.setData({sortIndex:Number(e.detail.value)});this.load()},
  detail(e:WechatMiniprogram.TouchEvent){navigation.openCompanion(e.currentTarget.dataset.id)},book(e:WechatMiniprogram.TouchEvent){const item=companionService.getById(e.currentTarget.dataset.id);if(!item)return;bookingStore.clear();bookingStore.update({companionMode:'selected',companionId:item.id,companionName:item.name,companionPrice:item.price});navigation.startBooking()},
  favorite(e:WechatMiniprogram.CustomEvent|WechatMiniprogram.TouchEvent){const id=(e as WechatMiniprogram.TouchEvent).currentTarget?.dataset?.id||(e as WechatMiniprogram.CustomEvent<{id:string}>).detail?.id;this.toggleFavorite(id)},toggleFavorite(id:string){const item=companionService.getById(id);if(!item)return;const result=favoriteService.toggle({id:`companion-${id}`,targetId:id,type:'companion',title:item.name,subtitle:item.tags.join(' · '),image:item.avatar,createdAt:new Date().toISOString()});if(result.loginRequired){this.setData({loginVisible:true,pendingFavorite:id});return}this.load(false)},loginSuccess(){const id=this.data.pendingFavorite;this.setData({loginVisible:false,pendingFavorite:''});if(id)this.toggleFavorite(id)},closeLogin(){this.setData({loginVisible:false,pendingFavorite:''})},retry(){this.setData({loading:true});this.load()},
})
