import { mockPatients } from '../mocks/patients'
import type { Patient, PatientInput, PatientSummary } from '../types/patient'
import { storage } from '../utils/storage'
import { StorageKeys } from '../utils/storage-keys'
// 正式上线前：身份证号、健康史和紧急联系方式必须改为服务端加密存储，禁止写入普通日志。
export const maskPhone = (phone: string) => phone.replace(/^(\d{3})\d{4}(\d{4})$/, '$1****$2')
export const maskIdCard = (value = '') => value.length >= 8 ? `${value.slice(0, 3)}${'*'.repeat(Math.max(4, value.length - 7))}${value.slice(-4)}` : ''
export const calculateAge = (birthday: string, now = new Date()) => { const date = new Date(`${birthday}T00:00:00`); let age = now.getFullYear() - date.getFullYear(); if (now.getMonth() < date.getMonth() || (now.getMonth() === date.getMonth() && now.getDate() < date.getDate())) age -= 1; return Math.max(0, age) }
class PatientStore { private patients: Patient[] = []; private ready = false; hydrate() { if (this.ready) return; const saved = storage.get<Patient[]>(StorageKeys.patients, []); const seeded = storage.get(StorageKeys.patientsSeeded, false); this.patients = saved.length ? saved : seeded ? [] : mockPatients.map((item) => ({ ...item })); this.ready = true; storage.set(StorageKeys.patientsSeeded, true); this.persist() } list(): PatientSummary[] { this.hydrate(); return this.patients.map(({ phone: _phone, idCard: _idCard, emergencyPhone: _emergencyPhone, ...safe }) => ({ ...safe })) } get(id: string) { this.hydrate(); const p = this.patients.find((item) => item.id === id); return p ? { ...p } : undefined } getDefault(): PatientSummary | undefined { this.hydrate(); const p = this.patients.find((item) => item.isDefault) || this.patients[0]; if (!p) return undefined; const { phone: _phone, idCard: _idCard, emergencyPhone: _emergencyPhone, ...safe } = p; return { ...safe } } save(input: PatientInput, id?: string) { this.hydrate(); const now = new Date().toISOString(); const original = id ? this.patients.find((item) => item.id === id) : undefined; const patient: Patient = { ...input, id: original?.id || `patient-${Date.now()}`, age: calculateAge(input.birthday), phoneMasked: maskPhone(input.phone), idCardMasked: maskIdCard(input.idCard), createdAt: original?.createdAt || now, updatedAt: now }; if (patient.isDefault || !this.patients.length) this.patients = this.patients.map((item) => ({ ...item, isDefault: false })); if (original) this.patients = this.patients.map((item) => item.id === id ? patient : item); else this.patients.push(patient); this.ensureDefault(); this.persist(); return { ...patient } } setDefault(id: string) { this.hydrate(); this.patients = this.patients.map((item) => ({ ...item, isDefault: item.id === id })); this.ensureDefault(); this.persist() } remove(id: string) { this.hydrate(); this.patients = this.patients.filter((item) => item.id !== id); this.ensureDefault(); this.persist() } private ensureDefault() { if (this.patients.length && !this.patients.some((item) => item.isDefault)) this.patients[0].isDefault = true } private persist() { storage.set(StorageKeys.patients, this.patients) } }
export const patientStore = new PatientStore()
