import { favoriteService } from '../../services/favorite'
import { hospitalService } from '../../services/hospital'
import { navigation } from '../../utils/navigation'

const PAGE_SIZE=4
Page({
  data:{query:'',districts:hospitalService.districts().map(id=>({id,name:id==='all'?'全部区域':id})),levels:[{id:'all',name:'全部等级'},{id:'三级甲等',name:'三级甲等'},{id:'其他',name:'其他'}],populars:[{id:false,name:'全部医院'},{id:true,name:'热门医院'}],districtIndex:0,levelIndex:0,popularIndex:0,allItems:[] as Array<Record<string,unknown>>,items:[] as Array<Record<string,unknown>>,visibleCount:PAGE_SIZE,hasMore:false,loading:true,error:false,loginVisible:false,pendingFavorite:''},
  onLoad(){this.load()},onShow(){if(!this.data.loading)this.load(false)},onPullDownRefresh(){this.load();wx.stopPullDownRefresh()},onReachBottom(){this.loadMore()},
  load(reset=true){try{const allItems=hospitalService.list({query:this.data.query,district:this.data.districts[this.data.districtIndex].id,level:this.data.levels[this.data.levelIndex].id,popularOnly:this.data.populars[this.data.popularIndex].id}).map(i=>({...i,hotDepartments:i.departmentGroups.flatMap(g=>g.departments).slice(0,4),serviceText:`支持 ${i.supportedServiceIds.length} 项陪诊服务`,favorited:favoriteService.isFavorite('hospital',i.id)}));const visibleCount=reset?PAGE_SIZE:Math.max(this.data.visibleCount,PAGE_SIZE);this.setData({allItems,items:allItems.slice(0,visibleCount),visibleCount,hasMore:visibleCount<allItems.length,loading:false,error:false})}catch{this.setData({loading:false,error:true})}},
  loadMore(){if(!this.data.hasMore)return;const visibleCount=this.data.visibleCount+PAGE_SIZE;this.setData({visibleCount,items:this.data.allItems.slice(0,visibleCount),hasMore:visibleCount<this.data.allItems.length})},
  search(e:WechatMiniprogram.CustomEvent<{value:string}>){this.setData({query:e.detail.value});this.load()},clear(){this.setData({query:''});this.load()},district(e:WechatMiniprogram.PickerChange){this.setData({districtIndex:Number(e.detail.value)});this.load()},level(e:WechatMiniprogram.PickerChange){this.setData({levelIndex:Number(e.detail.value)});this.load()},popular(e:WechatMiniprogram.PickerChange){this.setData({popularIndex:Number(e.detail.value)});this.load()},detail(e:WechatMiniprogram.CustomEvent<{id:string}>){navigation.openHospital(e.detail.id)},favorite(e:WechatMiniprogram.CustomEvent<{id:string}>){this.toggleFavorite(e.detail.id)},
  toggleFavorite(id:string){const item=hospitalService.getById(id);if(!item)return;const result=favoriteService.toggle({id:`hospital-${id}`,targetId:id,type:'hospital',title:item.name,subtitle:`${item.level} · ${item.district}`,createdAt:new Date().toISOString()});if(result.loginRequired){this.setData({loginVisible:true,pendingFavorite:id});return}this.load(false)},loginSuccess(){const id=this.data.pendingFavorite;this.setData({loginVisible:false,pendingFavorite:''});if(id)this.toggleFavorite(id)},closeLogin(){this.setData({loginVisible:false,pendingFavorite:''})},retry(){this.setData({loading:true});this.load()},
})
